server_config:
  host: 0.0.0.0
  port: 8080
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password
  POSTGRES_DB: database
  POSTGRES_HOST: localhost
  token: 19d7db49377f44a848632cee032403f4948729d9606be66379d5943033b19cf2






